cmake_minimum_required(VERSION 3.25)

add_subdirectory(Smooth)
add_subdirectory(Sharpen)
add_subdirectory(Pyramids)
add_subdirectory(Morphological)
add_subdirectory(LUT)
add_subdirectory(Scale)
add_subdirectory(Translation)
add_subdirectory(Rotation)
add_subdirectory(Skew)
add_subdirectory(Reflect)
add_subdirectory(Perspective)
add_subdirectory(inpainting)
add_subdirectory(inpainting2)
add_subdirectory(denoising)
